/**
 * Curated destination data for Hotels, Places, Packages, and Hero Visuals.
 * Grounded in real travel details for Goa, Kerala, Manali, Jaipur, and Rishikesh,
 * with adaptive fallbacks for other custom destinations.
 */

export const KNOWN_DESTINATIONS = ['Goa', 'Kerala', 'Manali', 'Jaipur', 'Rishikesh'];

export const DESTINATION_DETAILS = {
  Goa: {
    heroImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Sun-kissed beaches, Portuguese heritage & vibrant coastal nightlife',
    bestTimeToVisit: 'November to February',
    hotels: [
      {
        id: 'g1',
        name: 'Taj Exotica Resort & Spa',
        category: 'Luxury Beachfront',
        rating: 4.8,
        reviews: 2450,
        pricePerNight: 16500,
        image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=600&q=80',
        location: 'Benaulim, South Goa',
        amenities: ['Private Beach', 'Infinity Pool', 'Spa', 'Fine Dining', 'Free Wi-Fi'],
      },
      {
        id: 'g2',
        name: 'W Goa Beach Resort',
        category: 'Boutique Lifestyle',
        rating: 4.7,
        reviews: 1820,
        pricePerNight: 14000,
        image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=600&q=80',
        location: 'Vagator Beach, North Goa',
        amenities: ['Rock Pool', 'Cocktail Lounge', 'Spa', 'Sunset Deck'],
      },
      {
        id: 'g3',
        name: 'Santana Beach Resort',
        category: 'Comfort & Value',
        rating: 4.5,
        reviews: 3100,
        pricePerNight: 4800,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
        location: 'Candolim Beach',
        amenities: ['2 Swimming Pools', 'Beach Access', 'Restaurant', 'Free Breakfast'],
      },
      {
        id: 'g4',
        name: 'Zostel Plus South Goa',
        category: 'Backpacker & Social',
        rating: 4.6,
        reviews: 1240,
        pricePerNight: 1800,
        image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=600&q=80',
        location: 'Canacona / Palolem',
        amenities: ['Dorms & Private Rooms', 'Co-working Cafe', 'Community Events', 'Rooftop Lounge'],
      },
    ],
    places: [
      {
        id: 'gp1',
        name: 'Baga & Calangute Coast',
        category: 'Beach & Water Sports',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        timing: 'Open 24/7 (Water sports 9 AM - 6 PM)',
        fee: 'Free Entry (Activities ₹800 - ₹2,500)',
        description: 'Vibrant stretch famous for parasailing, jet-skiing, dolphin tours, and lively shacks.',
        tip: 'Book water sport combos through registered counters at the beach shack for best rates.',
      },
      {
        id: 'gp2',
        name: 'Fort Aguada & Lighthouse',
        category: 'Heritage & Scenic View',
        image: 'https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=600&q=80',
        timing: '9:30 AM – 6:00 PM',
        fee: '₹25 for Indians, ₹300 Foreigners',
        description: '17th-century Portuguese fortress overlooking the confluence of the Mandovi River and Arabian Sea.',
        tip: 'Visit in the late afternoon around 4:30 PM for breathtaking sunset photography.',
      },
      {
        id: 'gp3',
        name: 'Basilica of Bom Jesus',
        category: 'UNESCO World Heritage',
        image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=600&q=80',
        timing: '9:00 AM – 6:30 PM',
        fee: 'Free entry',
        description: 'Historic landmark in Old Goa holding the mortal remains of St. Francis Xavier.',
        tip: 'Modest dress code required. Pair with a visit to Se Cathedral right across the lawn.',
      },
      {
        id: 'gp4',
        name: 'Palolem Beach & Butterfly Island',
        category: 'Scenic & Peaceful Beach',
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        timing: 'Open all day',
        fee: 'Free (Boat rides ₹1,200/boat)',
        description: 'Crescent-shaped white sand bay lined with coconut palms and colorful wooden beach huts.',
        tip: 'Take an early morning boat ride to Butterfly Beach for dolphin spotting.',
      },
    ],
    packages: [
      {
        id: 'pkg1',
        title: 'Goa Coastal Vibes & Watersports',
        duration: '4 Nights / 5 Days',
        price: 19999,
        originalPrice: 26000,
        badge: 'Best Seller',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=600&q=80',
        inclusions: ['4-Star Candolim Resort', 'Daily Breakfast & Dinner', 'South Goa Private AC Cab', '5-in-1 Water Sports Combo', 'Mandovi Sunset Cruise'],
      },
      {
        id: 'pkg2',
        title: 'Romantic South Goa Serenity',
        duration: '3 Nights / 4 Days',
        price: 24500,
        originalPrice: 31000,
        badge: 'Honeymoon Special',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        inclusions: ['Luxury Beach Cottage in Palolem', 'Candlelight Shore Dinner', 'Dolphin Safari Boat Tour', 'Airport Transfers', 'Couples Ayurvedic Massage'],
      },
    ],
  },

  Kerala: {
    heroImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Gods Own Country – Emerald backwaters, mist-laden tea hills & Ayurvedic bliss',
    bestTimeToVisit: 'September to March',
    hotels: [
      {
        id: 'k1',
        name: 'Spice Tree Munnar',
        category: 'Hill View Luxury',
        rating: 4.9,
        reviews: 1400,
        pricePerNight: 13500,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80',
        location: 'Chinnakanal, Munnar',
        amenities: ['Mountain Valley Infinity Pool', 'Spa', 'Tea Tasting', 'Private Jacuzzi'],
      },
      {
        id: 'k2',
        name: 'Kumarakom Lake Resort',
        category: 'Heritage Backwater',
        rating: 4.8,
        reviews: 2100,
        pricePerNight: 18000,
        image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80',
        location: 'Kumarakom, Kottayam',
        amenities: ['Meandering Pool', 'Ayurveda Centre', 'Sunset Cruise', 'Traditional Villas'],
      },
      {
        id: 'k3',
        name: 'Alleppey Premium Houseboat',
        category: 'Signature Experience',
        rating: 4.7,
        reviews: 3200,
        pricePerNight: 9500,
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80',
        location: 'Vembanad Lake, Alleppey',
        amenities: ['AC Bedrooms', 'Personal Chef', 'All Meals Included', 'Private Sun Deck'],
      },
    ],
    places: [
      {
        id: 'kp1',
        name: 'Alleppey Backwaters & Canals',
        category: 'Backwater Houseboat Cruise',
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80',
        timing: 'Day cruises 11:30 AM – 5:30 PM',
        fee: 'Shikara from ₹1,000/hr, Houseboat ₹8,500/night',
        description: 'Cruising through lush palm-fringed lagoons, village canals, and open paddy fields.',
        tip: 'Book village canoeing tours to reach narrow canals where big houseboats cannot navigate.',
      },
      {
        id: 'kp2',
        name: 'Munnar Tea Plantations & Top Station',
        category: 'Nature & Hill Station',
        image: 'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=600&q=80',
        timing: '6:00 AM – 6:00 PM',
        fee: 'Free viewpoints / Tea Museum ₹150',
        description: 'Endless rolling emerald tea estates carpeted in mist, cascading waterfalls, and cool mountain air.',
        tip: 'Wake up early for the Kolukkumalai sunrise jeep trek for an unforgettable cloud-bed view.',
      },
      {
        id: 'kp3',
        name: 'Fort Kochi Heritage & Chinese Fishing Nets',
        category: 'Colonial History & Art',
        image: 'https://images.unsplash.com/photo-1578321272176-b7bbc067950f?auto=format&fit=crop&w=600&q=80',
        timing: 'Open daily',
        fee: 'Free entry',
        description: 'Port town blend of Portuguese, Dutch, and British history alongside quirky cafes and antique shops.',
        tip: 'Catch a traditional Kathakali classical dance performance at Kerala Kathakali Centre at 6 PM.',
      },
    ],
    packages: [
      {
        id: 'kpkg1',
        title: 'Gems of Kerala – Munnar & Alleppey',
        duration: '4 Nights / 5 Days',
        price: 22499,
        originalPrice: 29000,
        badge: 'Recommended',
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=600&q=80',
        inclusions: ['2 Nights Munnar Tea Resort', '1 Night Alleppey AC Houseboat', '1 Night Kochi Heritage Hotel', 'All Meals on Houseboat', 'Private Cab from Kochi Airport'],
      },
    ],
  },

  Manali: {
    heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Snowy Himalayan peaks, roaring Beas river & pine valley tranquility',
    bestTimeToVisit: 'March to June (Summer) or Dec to Feb (Snow)',
    hotels: [
      {
        id: 'm1',
        name: 'The Himalayan Resort & Spa',
        category: 'Castle Boutique',
        rating: 4.8,
        reviews: 980,
        pricePerNight: 12000,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80',
        location: 'Hadimba Road, Manali',
        amenities: ['Heated Pool', 'Victorian Fireplace', 'Orchard Views', 'Gourmet Dining'],
      },
      {
        id: 'm2',
        name: 'Manuallaya - The Resort Spa in the Himalayas',
        category: 'Valley Luxury',
        rating: 4.6,
        reviews: 1650,
        pricePerNight: 8500,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
        location: 'Sunny Side, Chadyari',
        amenities: ['Panoramic Beas Views', 'Spa & Sauna', 'Kids Zone', 'Multi-cuisine Restaurant'],
      },
    ],
    places: [
      {
        id: 'mp1',
        name: 'Solang Valley & Atal Tunnel',
        category: 'Adventure & Snow Activities',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
        timing: '8:00 AM – 6:00 PM',
        fee: 'Activities ₹1,000 - ₹3,500',
        description: 'Epic valley for paragliding, zorbing, skiing, and crossing into the surreal Lahaul Valley.',
        tip: 'Visit Solang early in the morning before 9:30 AM to beat tourist vehicle traffic.',
      },
      {
        id: 'mp2',
        name: 'Old Manali & Hadimba Temple',
        category: 'Cafe Culture & Ancient Wooden Shrine',
        image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80',
        timing: 'Temple 8:00 AM – 6:00 PM, Cafes till 11 PM',
        fee: 'Free',
        description: 'Bohemian riverside village packed with live music cafes, wood-fired pizza, and ancient cedar forest.',
        tip: 'Try trout fish and steaming momos at the riverside cafes in Old Manali.',
      },
    ],
    packages: [
      {
        id: 'mpkg1',
        title: 'Manali Alpine Thrill & Snow Tour',
        duration: '4 Nights / 5 Days',
        price: 17999,
        originalPrice: 23500,
        badge: 'Adventure Special',
        image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
        inclusions: ['4-Star Mountain View Resort', 'Solang Valley Adventure Day', 'Atal Tunnel & Sissu Day Trip', 'Breakfast & Dinner', 'Volvo Transfers from Delhi/Chandigarh'],
      },
    ],
  },

  Jaipur: {
    heroImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    tagline: 'The Pink City – Majestic palaces, formidable hill forts & royal Rajput gastronomy',
    bestTimeToVisit: 'October to March',
    hotels: [
      {
        id: 'j1',
        name: 'ITC Rajputana, Luxury Collection',
        category: 'Royal Heritage Luxury',
        rating: 4.8,
        reviews: 3100,
        pricePerNight: 12500,
        image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80',
        location: 'Palace Road, Jaipur',
        amenities: ['Kaya Kalp Royal Spa', 'Courtyard Pool', 'Peshawri Dining', 'Royal Decor'],
      },
      {
        id: 'j2',
        name: 'Alsisar Haveli - A Heritage Hotel',
        category: 'Classic Rajput Haveli',
        rating: 4.6,
        reviews: 2150,
        pricePerNight: 6200,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80',
        location: 'Sansar Chandra Road',
        amenities: ['Historic Frescoes', 'Heritage Courtyard Pool', 'Reading Room', 'Folk Music Nights'],
      },
    ],
    places: [
      {
        id: 'jp1',
        name: 'Amber Fort & Maota Lake',
        category: 'Hill Fortress & UNESCO Site',
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=600&q=80',
        timing: '8:00 AM – 5:30 PM (Night tour 6:30 – 9:15 PM)',
        fee: '₹100 Indians, ₹500 Foreigners',
        description: 'Imposing Rajput fort atop Cheel ka Teela featuring the Sheesh Mahal (Mirror Palace).',
        tip: 'Hire an official audio guide or licensed guide at the entrance for vivid history of the courtyards.',
      },
      {
        id: 'jp2',
        name: 'Hawa Mahal & City Palace',
        category: 'Royal Architecture & Bazaars',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        timing: '9:00 AM – 5:00 PM',
        fee: 'Hawa Mahal ₹50, City Palace ₹300',
        description: 'Iconic 953-window pink sandstone honeycomb facade designed for royal ladies to view street parades.',
        tip: 'Head to the rooftop Wind View Cafe directly across Hawa Mahal for the best photo angle.',
      },
    ],
    packages: [
      {
        id: 'jpkg1',
        title: 'Royal Rajasthan Heritage Trail',
        duration: '3 Nights / 4 Days',
        price: 18499,
        originalPrice: 24000,
        badge: 'Cultural Highlight',
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=600&q=80',
        inclusions: ['4-Star Heritage Haveli Stay', 'Private AC Chauffeur for Forts', 'Chokhi Dhani Royal Cultural Dinner', 'Daily Royal Breakfast', 'Monument Fast-Track Entry'],
      },
    ],
  },

  Rishikesh: {
    heroImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Yoga capital of the world, sacred Ganga Aarti & white-water river rapids',
    bestTimeToVisit: 'September to November & February to May',
    hotels: [
      {
        id: 'r1',
        name: 'Aloha On The Ganges',
        category: 'Riverside Resort & Spa',
        rating: 4.7,
        reviews: 2900,
        pricePerNight: 9800,
        image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=600&q=80',
        location: 'Tapovan, Rishikesh',
        amenities: ['Ganges Facing Infinity Pool', 'Daily Yoga Sessions', 'Ayurveda Spa', 'Riverside Deck'],
      },
      {
        id: 'r2',
        name: 'Camp AquaForest River Tents',
        category: 'Adventure Camping',
        rating: 4.5,
        reviews: 870,
        pricePerNight: 3500,
        image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=600&q=80',
        location: 'Shivpuri, Rishikesh',
        amenities: ['Swiss Tents with AC', 'Bonfire & BBQ', 'Rafting Assistance', 'Riverside Beach'],
      },
    ],
    places: [
      {
        id: 'rp1',
        name: 'Ganges White Water Rafting',
        category: 'Extreme Adventure',
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        timing: '8:00 AM – 4:00 PM',
        fee: '₹600 (12km) to ₹1,500 (26km Marine Drive stretch)',
        description: 'Tackle thrilling Grade III & IV rapids including Three Blind Mice, Roller Coaster, and Golf Course.',
        tip: 'Ensure your operator is Uttarakhand Tourism certified and provides quality lifejackets and helmets.',
      },
      {
        id: 'rp2',
        name: 'Triveni Ghat Evening Maha Aarti',
        category: 'Spiritual & Cultural Immersion',
        image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
        timing: 'Starts at sunset (6:00 PM – 7:15 PM)',
        fee: 'Free (Diya offerings ₹30 - ₹50)',
        description: 'Mesmerizing chantings, bells, and floating oil lamps lighting up the sacred river.',
        tip: 'Arrive by 5:15 PM to grab a peaceful seat on the ghat steps right near the priests.',
      },
    ],
    packages: [
      {
        id: 'rpkg1',
        title: 'Rishikesh Rafting & Yoga Retreat',
        duration: '2 Nights / 3 Days',
        price: 11999,
        originalPrice: 15500,
        badge: 'Top Value',
        image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
        inclusions: ['Riverside Swiss Tents Stay', '16km Shivpuri River Rafting', 'Cliff Jump & Body Surfing', 'All Buffet Meals & Evening Snacks', 'Guided Sunrise Yoga Session'],
      },
    ],
  },
};

/**
 * Helper to get destination details with intelligent fallback for custom places
 */
export function getDestinationData(destinationName) {
  if (!destinationName) return DESTINATION_DETAILS.Goa;
  
  const normalized = destinationName.trim().toLowerCase();
  for (const [key, val] of Object.entries(DESTINATION_DETAILS)) {
    if (key.toLowerCase() === normalized) {
      return { ...val, destinationName: key };
    }
  }

  // Fallback for custom or international destination
  return {
    heroImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80',
    tagline: `Discover the unforgettable wonders and vibrant culture of ${destinationName}`,
    bestTimeToVisit: 'Year-round depending on preferred season',
    hotels: [
      {
        id: 'cust-h1',
        name: `Grand Central Resort & Spa, ${destinationName}`,
        category: '4-Star Premium',
        rating: 4.6,
        reviews: 1420,
        pricePerNight: 8500,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
        location: `Prime Area, ${destinationName}`,
        amenities: ['Swimming Pool', 'Fine Dining', 'Free Wi-Fi', 'Spa'],
      },
      {
        id: 'cust-h2',
        name: `Boutique Heritage Suites, ${destinationName}`,
        category: 'Comfort & Style',
        rating: 4.5,
        reviews: 980,
        pricePerNight: 4500,
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80',
        location: `City Center, ${destinationName}`,
        amenities: ['Breakfast Included', 'Airport Shuttle', 'Terrace'],
      },
    ],
    places: [
      {
        id: 'cust-p1',
        name: `Iconic Landmark & Center of ${destinationName}`,
        category: 'Sightseeing & Culture',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80',
        timing: '9:00 AM – 6:00 PM',
        fee: 'Check local ticketing',
        description: `The top historical or cultural site in ${destinationName}, celebrating local architecture.`,
        tip: 'Visit in the early hours to avoid crowds.',
      },
      {
        id: 'cust-p2',
        name: `Local Market & Street Delights of ${destinationName}`,
        category: 'Food & Shopping',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        timing: '10:00 AM – 10:00 PM',
        fee: 'Free entry',
        description: 'Vibrant local stalls with authentic local cuisine, handicrafts, and souvenirs.',
        tip: 'Carry small local currency denominations for market vendors.',
      },
    ],
    packages: [
      {
        id: 'cust-pkg1',
        title: `Explore ${destinationName} All-Inclusive Holiday`,
        duration: '4 Nights / 5 Days',
        price: 21999,
        originalPrice: 28000,
        badge: 'Custom Tour',
        image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=80',
        inclusions: ['4-Star Hotel Accommodation', 'Daily Breakfast & Dinner', 'Full Day City Tour Cab', 'Sightseeing Tickets', 'Airport Transfers'],
      },
    ],
  };
}
